import type { AttentionStudent, StudentSubmissionCard } from "./types";

export const recentActivities = [
  ["20/06 22:15", "Nguyễn Minh Anh", "vừa nộp bài"],
  ["20/06 21:40", "Lê Hoàng Nam", "vừa nộp bài"],
  ["20/06 20:05", "Phạm Khánh Linh", "vừa nộp bài"],
  ["19/06 19:30", "Bạn đã giao bài cho lớp", ""],
];

export const attentionStudents: AttentionStudent[] = [
  { name: "Đỗ Quang Huy", tag: "Chưa nộp", desc: "Quá hạn 1 ngày", tone: "red" },
  { name: "Bùi Đức Anh", tag: "Nộp muộn", desc: "Trễ 35 phút", tone: "orange" },
  { name: "Ngô Thùy Dương", tag: "Điểm thấp", desc: "Bài này: 4.5", tone: "orange" },
];

export const studentSubmissions: StudentSubmissionCard[] = [
  {
    name: "Nguyễn Minh Anh",
    avatar: "👨🏻",
    status: "Cần chấm tự luận",
    statusTone: "orange",
    time: "20/06 22:15",
    mcq: "6/8 đúng",
    essay: "2/4 đã chấm",
    scoreLabel: "Điểm tạm tính",
    score: "6.5 / 10",
    scoreTone: "orange",
    action: "grade",
  },
  {
    name: "Trần Bảo Lan",
    avatar: "👩🏻",
    status: "Đã chấm",
    statusTone: "green",
    time: "20/06 20:10",
    mcq: "7/8 đúng",
    essay: "4/4 đã chấm",
    scoreLabel: "Điểm tổng",
    score: "8.5 / 10",
    scoreTone: "green",
    action: "view",
  },
  {
    name: "Lê Hoàng Nam",
    avatar: "👨🏻",
    status: "Nộp muộn",
    statusTone: "red",
    time: "20/06 23:45",
    mcq: "5/8 đúng",
    essay: "1/4 đã chấm",
    scoreLabel: "Điểm tạm tính",
    score: "5.0 / 10",
    scoreTone: "orange",
    action: "grade",
  },
  {
    name: "Phạm Khánh Linh",
    avatar: "👨🏻",
    status: "Đã chấm",
    statusTone: "green",
    time: "19/06 20:05",
    mcq: "8/8 đúng",
    essay: "4/4 đã chấm",
    scoreLabel: "Điểm tổng",
    score: "9.0 / 10",
    scoreTone: "green",
    action: "view",
  },
  {
    name: "Đỗ Quang Huy",
    avatar: "👨🏻",
    status: "Cần chấm tự luận",
    statusTone: "orange",
    time: "20/06 21:30",
    mcq: "6/8 đúng",
    essay: "0/4 đã chấm",
    scoreLabel: "Điểm tạm tính",
    score: "4.5 / 10",
    scoreTone: "orange",
    action: "grade",
  },
  {
    name: "Vũ Mai Phương",
    avatar: "👩🏻",
    status: "Đã chấm",
    statusTone: "green",
    time: "20/06 23:30",
    mcq: "8/8 đúng",
    essay: "3/4 đã chấm",
    scoreLabel: "Điểm tổng",
    score: "8.0 / 10",
    scoreTone: "green",
    action: "view",
  },
  {
    name: "Ngô Thùy Dương",
    avatar: "👩🏻",
    status: "Chưa nộp",
    statusTone: "gray",
    time: "Quá hạn 1 ngày",
    mcq: "-",
    essay: "-",
    scoreLabel: "Điểm",
    score: "- / 10",
    scoreTone: "black",
    action: "none",
  },
  {
    name: "Đặng Quốc Bảo",
    avatar: "🤓",
    status: "Đã chấm",
    statusTone: "green",
    time: "20/06 19:50",
    mcq: "7/8 đúng",
    essay: "4/4 đã chấm",
    scoreLabel: "Điểm tổng",
    score: "8.5 / 10",
    scoreTone: "green",
    action: "view",
  },
];
